# Generated by Django 4.2.2 on 2023-07-02 09:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_contract', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=6)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2048)),
                ('signing_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_customer', models.CharField(choices=[('Potential', 'Potential'), ('Existing', 'Existing')], max_length=9)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('company', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=2048)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.contract')),
            ],
        ),
    ]
