# Generated by Django 4.2.2 on 2023-07-02 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sales_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_sales', to='staff.employee'),
        ),
        migrations.AddField(
            model_name='contract',
            name='support_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_support', to='staff.employee'),
        ),
    ]
