# Generated by Django 4.2.2 on 2023-07-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_contract_signing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='signing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
