# Generated by Django 4.2.2 on 2023-07-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_event_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='email_customer',
            field=models.EmailField(default='bidon@site.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='representative',
            field=models.CharField(default='bidon', max_length=50),
            preserve_default=False,
        ),
    ]
